### ISSUE TITLE
Inline CSS breaks in panel list info

### ISSUE THREAD

**Issue by lukasleitsch** [avoskitchen/kirby-kitchen#15]
<img width="1433" alt="Bildschirmfoto 2023-09-07 um 12 28 45" src="https://github.com/avoskitchen/kirby-kitchen/assets/3009245/3f31c170-f927-414f-84c4-631eb749b846">

The inline CSS in the panel list info breaks in Kirby 3.9.6.1. I guess that the string will be escaped.

A workaround could be to remove the inline css and output the cuisine field directly like the category. Example: `category, cuisine`

@fabianmichael What do you think?

**Comment by lukasleitsch** [comment]
Another workaround is to overwrite the info field in the recipes.yml

```
tabs:
  recipes:
    sections:
      drafts:
        info: "{{ page.categoryTitle }}"
      published:
        info: "{{ page.categoryTitle }}"
      unlisted:
        info: "{{ page.categoryTitle }}"
```

**Comment by fabianmichael** [comment]
Yeah, lets better remove this hack and just output everything directly. AFAIK, in recent versions of Kirby, there’s also a table mode for listing pages, so there’s no need for any workarounds any longer for displaying advanced page info.

**Comment by fabianmichael** [comment]
Done in https://github.com/avoskitchen/kirby-kitchen/commit/7bd060479a1348d3ebaccb253d1f2cc413550418
